name: Lint

on:
  release:
    types: [ created ]
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
      - ".github/workflows/lint.yaml"
      - ".golangci.yml"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          args:
            -v
            --config=.golangci.yml
            --max-same-issues=50
